import { StyleSheet } from 'react-native';
import { Colors, THEME, fw } from '../themes/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: THEME.spacing.lg,
    paddingVertical: THEME.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.background,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: THEME.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerText: {
    flex: 1,
    marginLeft: THEME.spacing.md,
  },
  headerTitle: {
    fontSize: THEME.typography.size.xl,
    fontWeight: fw(THEME.typography.weight.heavy),
    color: Colors.textPrimary,
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
  },
  livePill: {
    minWidth: 40,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#fff',
  },
  offlineBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
    backgroundColor: '#fef3c7',
    paddingHorizontal: THEME.spacing.lg,
    paddingVertical: THEME.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#fde68a',
  },
  offlineText: {
    flex: 1,
    fontSize: THEME.typography.size.sm,
    color: '#92400e',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: THEME.spacing.lg,
    paddingBottom: THEME.spacing.xxxl,
  },
  heroCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    padding: THEME.spacing.lg,
    marginBottom: THEME.spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: THEME.spacing.lg,
  },
  heroIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: THEME.spacing.md,
    paddingVertical: 7,
  },
  statusBadgeText: {
    fontSize: THEME.typography.size.sm,
    fontWeight: fw(THEME.typography.weight.heavy),
  },
  heroTitle: {
    fontSize: THEME.typography.size.xxxl,
    lineHeight: 31,
    fontWeight: fw(THEME.typography.weight.heavy),
    color: Colors.textPrimary,
  },
  heroSub: {
    marginTop: 6,
    fontSize: THEME.typography.size.md,
    lineHeight: 20,
    color: Colors.textSecondary,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: Colors.surfaceAlt,
    overflow: 'hidden',
    marginTop: THEME.spacing.lg,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  progressFooter: {
    marginTop: THEME.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  progressText: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  progressPercent: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.heavy),
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: THEME.spacing.sm,
    marginBottom: THEME.spacing.lg,
  },
  infoCard: {
    width: '48.5%',
    minHeight: 118,
    borderRadius: THEME.borderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: '#fff',
    padding: THEME.spacing.md,
  },
  infoIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: THEME.spacing.sm,
  },
  infoLabel: {
    fontSize: THEME.typography.size.xs,
    color: Colors.textMuted,
    fontWeight: fw(THEME.typography.weight.bold),
    textTransform: 'uppercase',
  },
  infoValue: {
    marginTop: 5,
    fontSize: THEME.typography.size.md,
    lineHeight: 18,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  sectionCard: {
    backgroundColor: '#fff',
    borderRadius: THEME.borderRadius.lg,
    padding: THEME.spacing.lg,
    marginBottom: THEME.spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
    marginBottom: THEME.spacing.md,
  },
  sectionHeaderCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
  },
  sectionTitle: {
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.heavy),
    color: Colors.textPrimary,
  },
  detailPanel: {
    borderRadius: THEME.borderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: THEME.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  detailIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailText: {
    flex: 1,
    marginLeft: THEME.spacing.md,
  },
  detailLabel: {
    fontSize: THEME.typography.size.xs,
    color: Colors.textMuted,
    fontWeight: fw(THEME.typography.weight.bold),
    textTransform: 'uppercase',
  },
  detailValue: {
    marginTop: 4,
    fontSize: THEME.typography.size.md,
    lineHeight: 20,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.semibold),
  },
  orderItems: {
    gap: THEME.spacing.sm,
  },
  emptyOrderState: {
    borderRadius: THEME.borderRadius.md,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#cbd5e1',
    padding: THEME.spacing.md,
    backgroundColor: Colors.surface,
  },
  emptyOrderText: {
    fontSize: THEME.typography.size.md,
    lineHeight: 20,
    color: Colors.textSecondary,
  },
  orderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.md,
    backgroundColor: Colors.surface,
    padding: THEME.spacing.md,
    borderRadius: THEME.borderRadius.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  qtyBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyBadgeText: {
    color: Colors.textInverse,
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  orderMeta: {
    flex: 1,
  },
  orderItemName: {
    fontSize: THEME.typography.size.md,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  orderItemUnit: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  locationPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: THEME.borderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.glassAccent,
    padding: THEME.spacing.md,
  },
  locationPin: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: `${Colors.primary}30`,
  },
  locationMeta: {
    flex: 1,
    marginLeft: THEME.spacing.md,
  },
  locationTitle: {
    fontSize: THEME.typography.size.md,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.heavy),
  },
  locationValue: {
    marginTop: 5,
    fontSize: THEME.typography.size.sm,
    lineHeight: 17,
    color: Colors.textSecondary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  trackingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: THEME.spacing.md,
  },
  trackingStepText: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  timeline: {
    paddingTop: THEME.spacing.xs,
  },
  timelineItem: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'flex-start',
    position: 'relative',
  },
  stageCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    zIndex: 1,
  },
  stageCircleInactive: {
    backgroundColor: Colors.background,
    borderColor: Colors.border,
  },
  stageCircleCurrent: {
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
  },
  stageInfo: {
    flex: 1,
    marginLeft: THEME.spacing.md,
    paddingBottom: THEME.spacing.md,
  },
  stageName: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  stageNameInactive: {
    color: Colors.textSecondary,
  },
  stageNameActive: {
    color: Colors.textPrimary,
  },
  stageDesc: {
    marginTop: 3,
    fontSize: THEME.typography.size.sm,
    lineHeight: 17,
  },
  stageDescInactive: {
    color: Colors.textMuted,
  },
  stageDescActive: {
    color: Colors.textSecondary,
  },
  connector: {
    position: 'absolute',
    left: 16,
    top: 34,
    bottom: -2,
    width: 2,
  },
  connectorInactive: {
    backgroundColor: Colors.border,
  },
  confirmBtn: {
    minHeight: 52,
    backgroundColor: Colors.success,
    borderRadius: THEME.borderRadius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: THEME.spacing.sm,
    marginBottom: THEME.spacing.lg,
  },
  confirmBtnText: {
    color: Colors.textInverse,
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  finalMessage: {
    backgroundColor: Colors.successBg,
    borderWidth: 1,
    borderColor: Colors.success,
    borderRadius: THEME.borderRadius.lg,
    padding: THEME.spacing.lg,
    alignItems: 'center',
    marginBottom: THEME.spacing.lg,
  },
  finalText: {
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.success,
    marginTop: THEME.spacing.sm,
    marginBottom: 4,
  },
  finalSub: {
    fontSize: THEME.typography.size.md,
    color: Colors.textSecondary,
    textAlign: 'center',
  },
  helplines: {
    gap: THEME.spacing.sm,
  },
  helplineBtn: {
    minHeight: 62,
    borderLeftWidth: 4,
    borderRadius: THEME.borderRadius.md,
    backgroundColor: '#fff',
    paddingHorizontal: THEME.spacing.md,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  helplineName: {
    flex: 1,
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
  },
  helplinePhoneBtn: {
    marginRight: THEME.spacing.md,
    fontSize: THEME.typography.size.md,
    color: Colors.textSecondary,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  newRequestBtn: {
    backgroundColor: Colors.primary,
    marginHorizontal: THEME.spacing.lg,
    marginTop: THEME.spacing.sm,
    marginBottom: THEME.spacing.lg,
    paddingVertical: THEME.spacing.lg,
    borderRadius: THEME.borderRadius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  newRequestBtnText: {
    color: Colors.textInverse,
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.bold),
  },
});

export default styles;
