import { StyleSheet } from 'react-native';
import { Colors, THEME, fw } from '../themes/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  brandHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: THEME.spacing.md,
    paddingVertical: THEME.spacing.md,
    paddingHorizontal: THEME.spacing.lg,
    position: 'relative',
  },
  brandLogo: {
    position: 'absolute',
    left: THEME.spacing.lg,
  },
  brandTitle: {
    fontSize: 24,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.primary,
    letterSpacing: 0.5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: THEME.spacing.lg,
    paddingVertical: THEME.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholder: {
    width: 40,
  },
  headerTitle: {
    fontSize: THEME.typography.size.xxl,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
  },
  scrollContent: {
    paddingHorizontal: THEME.spacing.lg,
    paddingVertical: THEME.spacing.lg,
  },
  section: {
    marginBottom: THEME.spacing.xl,
  },
  sectionTitle: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
    marginBottom: THEME.spacing.md,
  },
  themeRow: {
    flexDirection: 'row',
    gap: THEME.spacing.md,
  },
  themeBtn: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: THEME.borderRadius.md,
    paddingVertical: THEME.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  themeBtnActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  themeBtnText: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
  },
  themeBtnTextActive: {
    color: Colors.textInverse,
  },
  themeInfoCard: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: THEME.borderRadius.md,
    padding: THEME.spacing.md,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
  },
  themeInfoText: {
    fontSize: THEME.typography.size.md,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.medium),
    flex: 1,
  },
  backendCard: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderRadius: THEME.borderRadius.md,
    padding: THEME.spacing.md,
  },
  backendHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: THEME.spacing.md,
  },
  statusIconWrap: {
    width: 44,
    height: 44,
    borderRadius: THEME.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: THEME.spacing.md,
  },
  backendTitleWrap: {
    flex: 1,
  },
  backendStatusText: {
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  backendSubtitle: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  urlBox: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: THEME.borderRadius.sm,
    padding: THEME.spacing.md,
    marginBottom: THEME.spacing.md,
  },
  urlLabel: {
    fontSize: THEME.typography.size.xs,
    color: Colors.textMuted,
    fontWeight: fw(THEME.typography.weight.bold),
    textTransform: 'uppercase',
    marginBottom: THEME.spacing.xs,
  },
  urlValue: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textPrimary,
    fontWeight: fw(THEME.typography.weight.medium),
  },
  warningCard: {
    backgroundColor: Colors.errorBg,
    borderWidth: 1,
    borderColor: Colors.error + '25',
    borderRadius: THEME.borderRadius.sm,
    padding: THEME.spacing.md,
    marginBottom: THEME.spacing.md,
  },
  warningTitle: {
    fontSize: THEME.typography.size.sm,
    color: Colors.error,
    fontWeight: fw(THEME.typography.weight.bold),
    flex: 1,
  },
  warningDescription: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    lineHeight: 19,
    marginTop: THEME.spacing.sm,
  },
  backendButton: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    borderRadius: THEME.borderRadius.md,
    paddingVertical: THEME.spacing.md,
    paddingHorizontal: THEME.spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  backendButtonDisabled: {
    opacity: 0.65,
  },
  backendButtonText: {
    flex: 1,
    fontSize: THEME.typography.size.lg,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textInverse,
    textAlign: 'center',
  },
  backendButtonIcon: {
    marginLeft: THEME.spacing.sm,
  },
  urlDisplay: {
    backgroundColor: Colors.surface,
    borderRadius: THEME.borderRadius.md,
    padding: THEME.spacing.md,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  urlText: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    fontFamily: 'monospace',
  },
  textInput: {
    backgroundColor: Colors.surface,
    borderRadius: THEME.borderRadius.md,
    padding: THEME.spacing.md,
    fontSize: THEME.typography.size.sm,
    color: Colors.textPrimary,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  presetsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: THEME.spacing.md,
  },
  presetBtn: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: Colors.surface,
    borderRadius: THEME.borderRadius.md,
    padding: THEME.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: THEME.spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 2,
  },
  presetLabel: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
  },
  presetUrl: {
    fontSize: THEME.typography.size.xs,
    color: Colors.textSecondary,
    textAlign: 'center',
  },
  infoBox: {
    marginHorizontal: THEME.spacing.lg,
    marginVertical: THEME.spacing.md,
    backgroundColor: Colors.info + '15',
    borderLeftWidth: 4,
    borderLeftColor: Colors.info,
    padding: THEME.spacing.md,
    borderRadius: THEME.borderRadius.md,
  },
  infoTitle: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.info,
    marginLeft: THEME.spacing.sm,
  },
  infoText: {
    fontSize: THEME.typography.size.sm,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  infoBold: {
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textPrimary,
  },
  statusBox: {
    marginHorizontal: THEME.spacing.lg,
    marginVertical: THEME.spacing.md,
    padding: THEME.spacing.md,
    borderRadius: THEME.borderRadius.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  statusText: {
    fontSize: THEME.typography.size.sm,
    fontWeight: fw(THEME.typography.weight.bold),
  },
  buttonContainer: {
    marginHorizontal: THEME.spacing.lg,
    marginVertical: THEME.spacing.lg,
    gap: THEME.spacing.md,
  },
  btn: {
    paddingVertical: THEME.spacing.md,
    borderRadius: THEME.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  testBtn: {
    backgroundColor: Colors.info,
  },
  saveBtn: {
    backgroundColor: Colors.success,
  },
  resetBtn: {
    backgroundColor: Colors.error,
  },
  btnText: {
    fontSize: THEME.typography.size.md,
    fontWeight: fw(THEME.typography.weight.bold),
    color: Colors.textInverse,
  },
});

export default styles;
